version: '3.8'
services:
  app:
    container_name: ttockclinic-app
    restart: always
    build:
      context: .
    expose:
      - "8080"

  nginx:
    container_name: ttockclinic-nginx
    image: nginx
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - app