version: '3.8'
services:
  app:
    container_name: ttockclinic-app
    restart: always
    build:
      context: .
    expose:
      - "8080"

  nginx:
    container_name: ttockclinic-nginx
    image: nginx:1.15-alpine
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./data/nginx/conf.d:/etc/nginx/conf.d
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    container_name: ttockclinic-certbot
    image: certbot/certbot:v0.36.0
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
